# .github/workflows/ci.yml

name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "export PATH=$HOME/.bun/bin:$PATH" >> $GITHUB_ENV

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun test

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "export PATH=$HOME/.bun/bin:$PATH" >> $GITHUB_ENV

      - name: Install dependencies
        run: bun install

      - name: Build and deploy
        run: |
          # Add deployment commands here
          # For example, deploying to Vercel
          # vercel deploy --prod